In [5]:
import numpy
print(numpy.__version__)

1.26.4


In [6]:
import numpy as np

### Python 列表不仅仅是一个简单的列表，其支持多种类型的数据结构

In [7]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [11]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### 但是正是这种灵活性是以存储和运行效率为代价的

## 创建numpy array

### 从0开始创建numpy array

In [13]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
l1 = list(range(5))
l1

[0, 1, 2, 3, 4]

In [17]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.6247326 , 0.92096759, 0.97764226],
       [0.18075626, 0.41221503, 0.24563702],
       [0.54085456, 0.79001712, 0.59800499]])

In [20]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.32304684, -1.40572414,  0.71520397],
       [ 0.23258125,  0.43569839, -0.6947687 ],
       [-1.21664343, -1.27936886,  1.1698229 ]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 7, 1],
       [7, 3, 0],
       [5, 9, 1]])

In [22]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

## Numpy Array 的一些属性

In [24]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [25]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6


In [26]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [27]:
print("dtype:", x3.dtype)

dtype: int32


### 元素访问

In [28]:
x1

array([4, 7, 9, 5, 3, 2])

In [29]:
x1[0]

4

In [30]:
x1[-1]

2

In [31]:
x2

array([[8, 2, 1, 3],
       [8, 2, 9, 4],
       [4, 2, 0, 6]])

In [32]:
print(x2[0, 0]) # x2[0][0] also works
print(x2[0][0])

8
8


In [33]:
x2[2, 1]

2

In [34]:
x2[2, -1]

6

In [30]:
x2[0, 0] = 12
x2

array([[12,  8,  2,  9],
       [ 3,  2,  3,  2],
       [ 4,  6,  2,  0]])

In [99]:
x1

array([8, 5, 8, 5, 4, 2])

In [98]:
x1.dtype

dtype('int32')

In [103]:
x1[0] = float('3.14159')  # this will be truncated!
x1

array([3, 5, 8, 5, 4, 2])

### 切片访问

In [35]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [37]:
x[:20]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [38]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [34]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x2

array([[0, 9, 6, 8],
       [7, 8, 3, 0],
       [1, 0, 4, 5]])

In [37]:
x2[:2, :3]  # two rows, three columns

array([[0, 9, 6],
       [7, 8, 3]])

In [38]:
x2[:3, ::2]  # all rows, every other column

array([[0, 6],
       [7, 3],
       [1, 4]])

In [39]:
print(x2[:, 0])  # first column of x2

[0 7 1]


In [40]:
print(x2[0, :])  # first row of x2

[0 9 6 8]


In [40]:
print(x2[0])  # equivalent to x2[0, :]

[8 2 1 3]


### 注意子数组返回的是试图View，而不是copy，注意和python 列表的区别

In [41]:
x2

array([[8, 2, 1, 3],
       [8, 2, 9, 4],
       [4, 2, 0, 6]])

In [42]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[8 2]
 [8 2]]


In [43]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  2]
 [ 8  2]]


In [44]:
print(x2)

[[99  2  1  3]
 [ 8  2  9  4]
 [ 4  2  0  6]]


### 用copy 函数

In [45]:
x2_sub_copy = x2[1:, :2].copy()
print(x2_sub_copy)

[[8 2]
 [4 2]]


In [46]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  2]
 [ 4  2]]


In [47]:
print(x2)

[[99  2  1  3]
 [ 8  2  9  4]
 [ 4  2  0  6]]


### 高级访问形式

In [48]:
x = np.random.randint(100, size=10)
x

array([16, 98, 14,  0,  9, 94, 44, 70, 76, 20])

In [49]:
x[x>50]

array([98, 94, 70, 76])

In [50]:
# [x[3], x[7], x[2]]

In [51]:
ind = [3, 1, 4]
x[ind]

array([ 0, 98,  9])

In [52]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [53]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

### 数组形状的调整

In [54]:
grid = np.arange(1, 21)
print(grid.shape)
grid

(20,)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
grid.reshape((10, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

### 数组的的组合和分裂

In [53]:
x = np.array([1, 2, 3])
y = np.array([3, 5, 1])
np.concatenate((x, y))
# np.concatenate([x, y])

array([1, 2, 3, 3, 5, 1])

In [54]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  5  1 99 99 99]


In [55]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [56]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [58]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [59]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [60]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [61]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [69]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Universal Functions

In [64]:
import numpy as np

In [65]:
def compute_reciprocals_list(values):
    output = []
    for i in range(len(values)):
        output.append(1 / values[i])
    return output

In [66]:
values = np.random.randint(1, 100, size=1000000).tolist()
%timeit compute_reciprocals_list(values)

213 ms ± 4.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [67]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [68]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

5.88 s ± 472 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [69]:
%timeit (1.0 / big_array)

6.72 ms ± 1.67 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [143]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [76]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [77]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [78]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [79]:
### 所有这些操作都是特定函数的封装，如+ 就是add 函数的一个wrapper

In [80]:
np.add(x, 2)

array([2, 3, 4, 5])

其他函数还包括


| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


### 绝对值

In [81]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [82]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [83]:
np.abs(x)

array([2, 1, 0, 1, 2])

### 其他常见数学函数

In [84]:
theta = np.linspace(0, np.pi, 3)

In [85]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [86]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [87]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [88]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [1]:
import pandas as pd

In [3]:
ss = pd.Series([1,3, 4.0, 'abc'])

In [4]:
ss

0      1
1      3
2    4.0
3    abc
dtype: object