In [1]:
# xding@zjgsu.edu.cn

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'2.1.1'

## The Pandas Series Object

### 1 维，可以从list，numpy array 创建

In [2]:
data_np = np.array([1, 2, 3,4, ])
data_np

array([1, 2, 3, 4])

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0, 1])

In [4]:
data

0    0.25
1    0.50
2    0.75
3    1.00
4    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  , 1.  ])

In [11]:
data.values.tolist()

[0.25, 0.5, 0.75, 1.0, 1.0]

In [12]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
data[1]

0.5

In [14]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### ``Series`` 作为 NumPy array 的扩展

###  series 与numpy 最大的区别在于，series 允许显式地创建索引index

In [15]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [16]:
data['b']

0.5

In [15]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [17]:
data[5]

C:\Users\dxywi\AppData\Local\Temp\ipykernel_6948\4250399272.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[5]


IndexError: index 5 is out of bounds for axis 0 with size 4

### ``Series`` 作为特殊的 dictionary

In [19]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [20]:
population['California']

38332521

In [24]:
ind = ['New York', 'Florida']
population[ind]

New York    19651127
Florida     19552860
dtype: int64

In [17]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [18]:
population[:4]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

### Series 对象创建的几种方式

Series 对象的创建基本上符合下面的语法：

```python
>>> pd.Series(data, index=index)
```

data 可以是numpy array，list，index默认的值为int 型的索引

In [20]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [21]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [21]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

##  Pandas DataFrame 对象

###   和Series 对象类似，  ``DataFrame`` 即可以看做是numpy array 的扩展，又可以看做是特殊的dictionary。

### 作为numpy array 的扩展

In [21]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [22]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

,population,area
California,38332521,423967
Texas,26448193,695662
New York,19651127,141297
Florida,19552860,170312
Illinois,12882135,149995


In [22]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

In [36]:
states.values[0]

array([38332521,   423967], dtype=int64)

In [29]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [30]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame 作为特殊的dictionary

In [24]:
states

,population,area
California,38332521,423967
Texas,26448193,695662
New York,19651127,141297
Florida,19552860,170312
Illinois,12882135,149995


In [25]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [31]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [32]:
pd.DataFrame(population, columns=['population'])

,population
California,38332521
Texas,26448193
New York,19651127
Florida,19552860
Illinois,12882135


### 从含有许多字典的list 中创建dataframe

In [28]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [29]:
data_pd = pd.DataFrame(data)
data_pd

,a,b
0,0,0
1,1,2
2,2,4


In [39]:
# 如果某些key 不存在会发生什么？
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

,a,b,c
0,1.0,2,NaN
1,NaN,3,4.0


In [33]:
# From a dictionary of Series objects
pd.DataFrame({'population': population,
              'area': area})

,population,area
California,38332521,423967
Texas,26448193,695662
New York,19651127,141297
Florida,19552860,170312
Illinois,12882135,149995


In [34]:
#  From a two-dimensional NumPy array
data_foo = pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])
data_foo

,foo,bar
a,0.770294,0.303646
b,0.678037,0.592460
c,0.232248,0.310876


##   Pandas Index 对象

In [35]:
data_foo
data_foo.index

Index(['a', 'b', 'c'], dtype='object')

In [36]:
ind = data_foo.index

In [37]:
ind[1]

'b'

In [38]:
ind[::2]

Index(['a', 'c'], dtype='object')

In [39]:
# Index as immutable array
ind[1] = 0

TypeError: Index does not support mutable operations

## 数据的索引和选取

### Series 对象

In [23]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [24]:
data['b']

0.5

In [25]:
'a' in data

True

In [26]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [44]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [41]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [42]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [45]:
data > 0.3

a    False
b     True
c     True
d     True
dtype: bool

In [52]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [53]:
indx = ['a', 'c']

In [54]:
# fancy indexing
data[indx]

a    0.25
c    0.75
dtype: float64

### Indexers: loc, iloc


In [46]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [30]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [31]:
# explicit index when indexing
data[1]

'a'

In [49]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [59]:
data

1    a
3    b
5    c
dtype: object

In [60]:
data[1]

'a'

In [51]:
data.iloc[1]  # implicit indexing

'b'

In [52]:
data.loc[1:3]

1    a
3    b
dtype: object

### Dataframe 对象

In [53]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

,area,pop
California,423967,38332521
Texas,695662,26448193
New York,141297,19651127
Florida,170312,19552860
Illinois,149995,12882135


In [54]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [66]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [67]:
data.area is data['area']

True

In [55]:
data['density'] = data['pop'] / data['area']
data

,area,pop,density
California,423967,38332521,90.413926
Texas,695662,26448193,38.018740
New York,141297,19651127,139.076746
Florida,170312,19552860,114.806121
Illinois,149995,12882135,85.883763


In [60]:
data.iloc[0]

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [61]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [70]:
data.T

,California,Texas,New York,Florida,Illinois
area,4.239670e+05,6.956620e+05,1.412970e+05,1.703120e+05,1.499950e+05
pop,3.833252e+07,2.644819e+07,1.965113e+07,1.955286e+07,1.288214e+07
density,9.041393e+01,3.801874e+01,1.390767e+02,1.148061e+02,8.588376e+01


In [71]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [73]:
# equivalent to the following
data.iloc[0]

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [74]:
data.iloc[:3, :2]

,area,pop
California,423967,38332521
Texas,695662,26448193
New York,141297,19651127


In [75]:
data.loc[:'Illinois', :'pop']

,area,pop
California,423967,38332521
Texas,695662,26448193
New York,141297,19651127
Florida,170312,19552860
Illinois,149995,12882135


In [76]:
data.loc[data.density > 100, ['pop', 'density']]

,pop,density
New York,19651127,139.076746
Florida,19552860,114.806121


In [77]:
data.iloc[0, 2] = 90
data

,area,pop,density
California,423967,38332521,90.000000
Texas,695662,26448193,38.018740
New York,141297,19651127,139.076746
Florida,170312,19552860,114.806121
Illinois,149995,12882135,85.883763


## 常见的统计

In [43]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [44]:
ser.sum()

2.811925491708157

In [45]:
ser.mean()

0.5623850983416314

In [47]:
df = pd.DataFrame({'A': rng.rand(5),
                   'B': rng.rand(5)})
df

,A,B
0,0.183405,0.611853
1,0.304242,0.139494
2,0.524756,0.292145
3,0.431945,0.366362
4,0.291229,0.456070


In [48]:
df.mean()

A    0.347115
B    0.373185
dtype: float64

In [49]:
df.mean(axis='columns') # or use axis=1

0    0.397629
1    0.221868
2    0.408451
3    0.399153
4    0.373650
dtype: float64

###  Planets Data

### available via the [Seaborn package](http://seaborn.pydata.org/)

In [50]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [51]:
type(planets)

pandas.core.frame.DataFrame

In [53]:
planets.head(10)

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300,7.10,77.40,2006
1,Radial Velocity,1,874.774,2.21,56.95,2008
2,Radial Velocity,1,763.000,2.60,19.84,2011
3,Radial Velocity,1,326.030,19.40,110.62,2007
4,Radial Velocity,1,516.220,10.50,119.47,2009
5,Radial Velocity,1,185.840,4.80,76.39,2008
6,Radial Velocity,1,1773.400,4.64,18.15,2002
7,Radial Velocity,1,798.500,NaN,21.41,1996
8,Radial Velocity,1,993.300,10.30,73.10,2008
9,Radial Velocity,2,452.800,1.99,74.79,2010


In [49]:
type(planets)

pandas.core.frame.DataFrame

In [54]:
planets.dropna().describe()

,number,orbital_period,mass,distance,year
count,498.00000,498.000000,498.000000,498.000000,498.000000
mean,1.73494,835.778671,2.509320,52.068213,2007.377510
std,1.17572,1469.128259,3.636274,46.596041,4.167284
min,1.00000,1.328300,0.003600,1.350000,1989.000000
25%,1.00000,38.272250,0.212500,24.497500,2005.000000
50%,1.00000,357.000000,1.245000,39.940000,2009.000000
75%,2.00000,999.600000,2.867500,59.332500,2011.000000
max,6.00000,17337.500000,25.000000,354.000000,2014.000000


In [59]:
df = pd.read_csv('hello.txt',header=None)

In [60]:
df

,0,1,2
0,name,age,grade
1,ding,100,200
2,wang,200,311
